import React, { useState } from 'react';
import { FileText, Copy, Check, Sparkles, BrainCircuit } from 'lucide-react';
import { ContactBriefData } from '../../types/api';

interface NarrativeSummaryProps {
  brief: ContactBriefData;
}

export const NarrativeSummary: React.FC<NarrativeSummaryProps> = ({ brief }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(brief.summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-6 shadow-sm space-y-4">
      <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-400 flex items-center justify-center">
            <BrainCircuit className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-base font-bold text-slate-900 dark:text-slate-100">
              Synthesized Account Narrative
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Generated by Hindsight from call transcripts, emails, and CRM notes
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={handleCopy}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 transition active:scale-95"
          title="Copy summary to clipboard"
        >
          {copied ? (
            <>
              <Check className="w-3.5 h-3.5 text-emerald-500" />
              <span className="text-emerald-600 dark:text-emerald-400 font-semibold">Copied</span>
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5" />
              <span>Copy Brief</span>
            </>
          )}
        </button>
      </div>

      <div className="relative p-4 rounded-xl bg-slate-50/70 dark:bg-slate-800/40 border border-slate-100 dark:border-slate-800/80">
        {/* Render purely as safe plain text string */}
        <p className="text-sm text-slate-800 dark:text-slate-200 leading-relaxed whitespace-pre-line font-normal">
          {brief.summary}
        </p>
      </div>

      <div className="flex flex-wrap items-center justify-between gap-2 pt-1 text-[11px] text-slate-500 dark:text-slate-400">
        <span className="inline-flex items-center gap-1 text-indigo-600 dark:text-indigo-400 font-medium">
          <Sparkles className="w-3 h-3" /> Auto-refreshes before upcoming meetings
        </span>
        <span>Model: Hindsight-Memory-v2.4 (Groq Engine)</span>
      </div>
    </div>
  );
};
